### ISSUE TITLE
Text does not show the value of progress bar when a Quest is inReview

### ISSUE THREAD

**Issue by adarshajit** [quest-chains/dapp#48]
Currently we are only displaying the `progress bar value` when a `quest` is completed

![Screenshot from 2022-10-01 14-39-09](https://user-images.githubusercontent.com/50659234/193402156-2b4f65b8-6248-459a-ab7e-cc0a16c7d91b.png)

**Comment by vidvidvid** [comment]
oh but it is meant to be like that. the progress here is still 0%, because the user hasn't completed any quests yet, however submissions for 1 out of 3 quests are currently in review. maybe we could add the % of pending submissions into brackets next to the percentage of completed quests, like `0% (30%)`. let's ask dave - he's our product designer
